### PR TITLE
 Adeed loading animation on page load

### PR DESCRIPTION
**Pull request by programmerraja**
#8 hey can you take look on it 

https://user-images.githubusercontent.com/44333589/193440747-c9ef790f-cdd6-4a27-89b5-85f9c708e547.mp4

### CODE REVIEW

**Review by mittal-parth — COMMENTED** [review]
@programmerraja, that looks awesome! ✨
But adding the loading screen feels like that Hero section is lagging or stuttering. 
I think the animation on Hero section would need to be changed. It shouldn't reload but rather load as soon as the loading animation finishes. 
Either the `whileInView` will have to be changed to some other animation or simply removed.

It would be great if you could add a screen recording for both versions. You can use the ScreenRec app for screen recording. Thanks again!

**Comment by programmerraja** [comment]
Ok i will do according to your suggestions

**Comment by mittal-parth** [comment]
> then we can remove the animation on hero page that will be better what's your opinion bro @mittal-parth

@programmerraja  Can you put a preview of that?

**Comment by programmerraja** [comment]
Preview with diiferent animation
[screen-capture.webm](https://user-images.githubusercontent.com/44333589/193449985-006dfd4e-3fdf-40f5-9540-3ed950de85d9.webm)


Preview without animation 
[screen-capture (1).webm](https://user-images.githubusercontent.com/44333589/193449995-4485de80-6477-4ad0-81fb-ec9795ed5f6b.webm)

@mittal-parth Which one you like ?

**Comment by mittal-parth** [comment]
> Preview with diiferent animation [screen-capture.webm](https://user-images.githubusercontent.com/44333589/193449985-006dfd4e-3fdf-40f5-9540-3ed950de85d9.webm)
@programmerraja this looks great! You can push the changes.

**Comment by programmerraja** [comment]
> > Preview with diiferent animation [screen-capture.webm](https://user-images.githubusercontent.com/44333589/193449985-006dfd4e-3fdf-40f5-9540-3ed950de85d9.webm)
> 
> @programmerraja this looks great! You can push the changes.

@mittal-parth Done brother

**Comment by mittal-parth** [comment]
@programmerraja that looks amazing!! 
Thank you for the contribution! 💙 Merging!

**Comment by mittal-parth** [comment]
Would be great if you can make a feature branch from next time and do the changes!

**Comment by programmerraja** [comment]
@mittal-parth thanks for your kind words

**Comment by programmerraja** [comment]
> Would be great if you can make a feature branch from next time and do the changes!

Ok I will do here after

**Pull request merged**
