### PR TITLE
Add dark theme styling to scrollbar

### LINKED ISSUE #27: Custom scrollbar with dark theme
### Styling the scrollbar

Hello, I would like to implement some styling to make the scrollbar have the same dark theme as the website.
Please let me know if it interests you, if it does, assign me and I will happily open a PR with the following code, the `--primary` and `--secondary` color variables, names, values are subject to change to respect the project styling.

```css
:root {
  --primary: #363636;
  --secondary: lightblue;
}

/* Firefox */
* {
  scrollbar-width: thin;
  scrollbar-color: var(--secondary) var(--primary);
}

/* Chrome, Edge, and Safari */
*::-webkit-scrollbar {
  width: 15px;
}

*::-webkit-scrollbar-track {
  background: var(--primary);
  border-radius: 0px;
}

*::-webkit-scrollbar-thumb {
  background-color: var(--secondary);
  border-radius: 14px;
  border: 3px solid var(--primary);
}
```

**Before**

BEFORE

**After**

AFTER

### PR DESCRIPTION
**Pull request by mateusabelli**
## Description

Added new styles for the scrollbar to better fit the website theme, it works for chromium based browsers and firefox.

Fixes #27

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by mittal-parth** [comment]
@mateusabelli thanks for adding the clean code with clear commits and PR messages.
I wonder how it will look if the scroll bar background is exactly same as the website background?

**Comment by mateusabelli** [comment]
Hello @mittal-parth, using the same `primary` and `secondary` colors in `tailwind.config.cjs` it would look like this.

image

This is with the previous `lightblue` color from the issue screenshots

image


You can check a live preview of  this by accessing the [preview deployment](https://deploy-preview-28--parthmittal.netlify.app/) and changing the values of the `scrollbar-primary` and `scrollbar-secondary` in the dev tools

image

**Comment by mittal-parth** [comment]
@mateusabelli thanks for the detailed screenshots!
I think we can go ahead with 
```
 --scrollbar-primary: #00040f;
 --scrollbar-secondary: lightblue;
```

**Comment by mateusabelli** [comment]
That's great @mittal-parth, I've updated the PR with the changes

**Review by mittal-parth — APPROVED** [review]

**Comment by mittal-parth** [comment]
@mateusabelli Thanks for adding the cool change! Merged!

**Pull request merged**
