### PR TITLE
Misc: Cleanup warnings

### LINKED ISSUE #66: Misc: Cleanup the React warnings
There are some warnings generated on the console right now:

- [ ] Warning: ForwardRef: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.
- [x] Warning: Each child in a list should have a unique "key" prop (4 times)
- [x] Warning: Invalid DOM property `class`. Did you mean `className`?
- [x] Warning: validateDOMNesting(...): `<div> cannot appear as a descendant of <p>`.
- [x] Warning: <AiFillGithub /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.

Please fix these. Some are pretty straightforward. The last one might require some debugging.

### PR DESCRIPTION
**Pull request by Nitheesh-2003**
- Fixed the warnings which arises due to several reasons,
- Also, made some UI fixes
- Can't fix the `defaultProp` warning. This is because memo is not used in the actual code but it comes from the third party libraries so we can't fix that. I have upgraded the third party packages as well everything is up-to date. So it won't cause any issue.
- Other than that all the warnings are fixed.

Closes #66

### CODE REVIEW

**Comment by Nitheesh-2003** [comment]
- Fixed the warnings which arises due to several reasons,
- Also, made some UI fixes
- Can't fix the `defaultProp` warning. This is because memo is not used in the actual code but it comes from the third party libraries so we can't fix that. I have upgraded the third party packages as well everything is up-to date. So it won't cause any issue.

**Comment by Nitheesh-2003** [comment]
I have created the PR, can you please review it and confirm

**Comment by mittal-parth** [comment]
Hey, I’ll review it in a while and get back

**Comment by mittal-parth** [comment]
> Can't fix the defaultProp warning. 

Sounds good. One nitpick. Try writing better commit messages even if the changes are small and use the imperative tense for commits. (Like Add xyz features instead of added xyz features)

Looks good overall, merged! :)

Thanks!

**Comment by Nitheesh-2003** [comment]
Thanks for the feedback @mittal-parth, especially with the example. Overall a good experience.

Thanks,

**Comment by mittal-parth** [comment]
Thanks @Nitheesh-2003! Would love if you could leave a star! 💙

**Comment by Nitheesh-2003** [comment]
Sure @mittal-parth

**Pull request merged**
