### PR TITLE
footer padding fixed #24

### LINKED ISSUE #24: Increase footer padding on tablets
image

The left padding on the footer for the tablet viewport is too less. Add padding on the left only for tablets.

### PR DESCRIPTION
**Pull request by Ahnaf-codes**
Added 1.5 rem padding to left of footer

### CODE REVIEW

**Comment by Ahnaf-codes** [comment]
@mittal-parth its done

**Comment by Ahnaf-codes** [comment]
@mittal-parth its done

**Review by mittal-parth — CHANGES_REQUESTED** [review]
@Ahnaf-codes the padding is also showing up on laptops and bigger viewports. It should only be for laptops.
Also, please indent the code properly. It should be 4 spaces not 8.

**Comment by Ahnaf-codes** [comment]
@mittal-parth done

**Comment by mittal-parth** [comment]
@Ahnaf-codes great, the padding looks right now.
Please indent using 4 spaces and not 8, and I can merge it.

**Comment by Ahnaf-codes** [comment]
Its done. @mittal-parth

**Comment by mittal-parth** [comment]
@Ahnaf-codes ah I am so sorry, it had to be 2 spaces and not 4 😞. So sorry for the inconvenience

**Comment by Ahnaf-codes** [comment]
@mittal-parth its done

**Comment by mittal-parth** [comment]
@Ahnaf-codes Merged!
I had meant using 2 spaces for the entire file and not just that changed line. 
Rest I rebased it off main, resolved merge conflicts and merged.

**Pull request merged**
